- hosts: 192.168.31.21
  remote_user: root
  roles:
    - { role: redis, roles_name: master, bind_ip: "{{ ansible_ssh_host }}" }

- hosts: 192.168.31.23
  remote_user: root
  roles:
    - { role: redis, roles_name: slave, bind_ip: "{{ ansible_ssh_host }}", master_ip: 192.168.31.21, master_port: 7379}
